# Generated by Django 4.2.2 on 2023-06-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0003_customuser_is_active_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
    ]
