# Generated by Django 4.2.2 on 2023-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
